/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type PricingConfig = {
  _id: string;
  _type: "pricingConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  extraPets?: {
    onePet: number;
    twoPets: number;
  };
  specialBackground: number;
  framePrices?: {
    mini: number;
    medium: number;
    large: number;
  };
  isActive: boolean;
  validFrom: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  price: number;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category: "retratos";
  size: "mini" | "medium" | "large";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  text?: string;
};

export type Painting = {
  _id: string;
  _type: "painting";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  aboutMe?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    text?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  faqItems?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  testimonials?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "testimonial";
  }>;
  featuredPaintings?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "painting";
  }>;
  differentiators?: Array<{
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imagePosition?: "left" | "right";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Slug | PricingConfig | Product | Testimonial | Painting | SiteSettings | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: allPaintingsQuery
// Query:   *[_type == 'painting'] {      _id,  name,  "image": image.asset->url  }
export type AllPaintingsQueryResult = Array<{
  _id: string;
  name: string | null;
  image: string | null;
}>;
// Variable: featuredPaintingsQuery
// Query:   *[_type == "siteSettings"][0].featuredPaintings[] -> {      _id,  name,  "image": image.asset->url  }
export type FeaturedPaintingsQueryResult = Array<{
  _id: string;
  name: string | null;
  image: string | null;
}> | null;
// Variable: allProductsQuery
// Query:   *[_type == "product"] | order(    select(      size == "mini" => 1,      size == "medium" => 2,      size == "large" => 3,      4    )  ) {      _id,  name,  description,  price,  "images": images[].asset->url,  category,  size  }
export type AllProductsQueryResult = Array<{
  _id: string;
  name: string;
  description: string;
  price: number;
  images: Array<string | null>;
  category: "retratos";
  size: "large" | "medium" | "mini";
}>;
// Variable: productByIdQuery
// Query:   *[_type == "product" && _id == $id][0] {    _id,    name,    description,    price,    "images": images[].asset->url,    category,    size  // Agregar este campo  }
export type ProductByIdQueryResult = {
  _id: string;
  name: string;
  description: string;
  price: number;
  images: Array<string | null>;
  category: "retratos";
  size: "large" | "medium" | "mini";
} | null;
// Variable: productsByIdsQuery
// Query:   *[_type == "product" && _id in $ids] {      _id,  name,  description,  price,  "images": images[].asset->url,  category,  size  }
export type ProductsByIdsQueryResult = Array<{
  _id: string;
  name: string;
  description: string;
  price: number;
  images: Array<string | null>;
  category: "retratos";
  size: "large" | "medium" | "mini";
}>;
// Variable: activePricingConfigQuery
// Query:   *[_type == "pricingConfig" && isActive == true] | order(validFrom desc)[0] {    _id,    name,    extraPets,    specialBackground,    framePrices,    isActive,    validFrom  }
export type ActivePricingConfigQueryResult = {
  _id: string;
  name: string;
  extraPets: {
    onePet: number;
    twoPets: number;
  } | null;
  specialBackground: number;
  framePrices: {
    mini: number;
    medium: number;
    large: number;
  } | null;
  isActive: boolean;
  validFrom: string;
} | null;
// Variable: siteSettingsQuery
// Query:   *[_type == "siteSettings"][0] {    title,    subtitle,    aboutMe {      "image": image.asset->url,      text    },    heroImage,    faqItems,    testimonials[] -> {      _id,      name,      image,      text    },    featuredPaintings[] -> {        _id,  name,  "image": image.asset->url    },    differentiators[] {      title,      description,      "image": image.asset->url,      imagePosition    }  }
export type SiteSettingsQueryResult = {
  title: string | null;
  subtitle: string | null;
  aboutMe: {
    image: string | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  faqItems: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }> | null;
  testimonials: Array<{
    _id: string;
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    text: string | null;
  }> | null;
  featuredPaintings: Array<{
    _id: string;
    name: string | null;
    image: string | null;
  }> | null;
  differentiators: Array<{
    title: string | null;
    description: string | null;
    image: string | null;
    imagePosition: "left" | "right" | null;
  }> | null;
} | null;
