/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XrhePXuq1wd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogFooter } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Wallet } from '@mercadopago/sdk-react';

export function ComissionForm({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className='sm:max-w-[600px]'>
        <div className='grid gap-6'>
          <div className='grid gap-2'>
            <h2 className='text-2xl font-bold'>Información de Contacto</h2>
            <div className='grid gap-4 md:grid-cols-2'>
              <div className='grid gap-2'>
                <Label htmlFor='nombre'>Nombre</Label>
                <Input id='nombre' placeholder='Ingresa tu nombre' />
              </div>
              <div className='grid gap-2'>
                <Label htmlFor='email'>Correo Electrónico</Label>
                <Input id='email' type='email' placeholder='ejemplo@email.com' />
              </div>
            </div>
            <div className='grid gap-4 md:grid-cols-2'>
              <div className='grid gap-2'>
                <Label htmlFor='direccion'>Dirección</Label>
                <Input id='direccion' placeholder='Ingresa tu dirección' />
              </div>
              <div className='grid gap-2'>
                <Label htmlFor='telefono'>Teléfono</Label>
                <Input id='telefono' type='tel' placeholder='123-456-7890' />
              </div>
            </div>
          </div>
          <div className='grid gap-2'>
            <h2 className='text-2xl font-bold'>Información de la Mascota</h2>
            <div className='grid gap-2'>
              <Label htmlFor='nombre-mascota'>Nombre de la Mascota</Label>
              <Input id='nombre-mascota' placeholder='Ingresa el nombre de tu mascota' />
            </div>
            <div className='grid gap-2'>
              <Label htmlFor='fotos-mascota'>Fotos de la Mascota</Label>
              <div>
                <div className='flex flex-col items-center justify-center h-48 border-2 border-dashed rounded-md border-muted'>
                  <UploadIcon className='w-12 h-12 text-muted-foreground' />
                  <p className='mt-2 text-sm text-muted-foreground'>
                    Arrastra y suelta tus fotos aquí o haz clic para seleccionar archivos.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <DialogFooter>
          <div>
            <Button type='submit'>Enviar</Button>

            <Wallet
              initialization={{
                preferenceId: '1931267094-5c6abc91-bd78-40a7-96c3-4ded683a6979',
              }}
            />
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function UploadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4' />
      <polyline points='17 8 12 3 7 8' />
      <line x1='12' x2='12' y1='3' y2='15' />
    </svg>
  );
}
